name: Approve Wolpert Pushes
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  wolpert:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'wolpert'
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: auto-approve
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
